[package]
name = "runtime"
version = "0.1.0"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ovis_runtime"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
