[package]
name = "ovis"
version = "0.1.0"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

[dependencies]
cranelift = "0.63.0"
cranelift-module = "0.63.0"
cranelift-faerie = "0.63.0"
peg = "0.6.2"
target-lexicon = "0.10.0"
